variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

stages:
  - code-analysis

code-analysis:
  stage: code-analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
