version: "3.8"

services:
  postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0745"
      POSTGRES_DB: "studyroom"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  studyroom:
    build: .
    container_name: my-studyroom-c1
    environment:
      DB_NAME: "studyroom"
      DB_USER: "postgres"
      DB_USER_PASSWORD: "0745"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    command: >
      sh -c "python /app/manage.py migrate
      && python /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

volumes:
  postgres-data:
